# Generated by Django 4.2.5 on 2023-09-29 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, upload_to='company_covers/')),
                ('profile_image', models.ImageField(blank=True, upload_to='company_profiles/')),
                ('description', models.TextField(blank=True)),
                ('admins', models.ManyToManyField(related_name='admin_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
