"""
Django settings for blogzone project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lz%4h&@t%q5=clywjs**a0)%1o=c5)#5xm1c@62l#kbp@t!=37'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'ckeditor',
    'ckeditor_uploader',

    
    'blog',
    'blog.templatetags',
    'company',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogzone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogzone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Static files (CSS, JavaScript, images)
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# Static root for production

STATIC_ROOT = os.path.join(BASE_DIR, 'static/static_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # CKEditor settings
# CKEDITOR_UPLOAD_PATH = 'uploads/'
# CKEDITOR_BASEPATH = "static/static_root/ckeditor/ckeditor/"
# CKEDITOR_FILENAME_GENERATOR = 'utils.get_filename'
# CKEDITOR_IMAGE_BACKEND = 'ckeditor_uploader.backends.PillowBackend'

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#     },
# }


from ckeditor.configs import DEFAULT_CONFIG  # noqa


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "ckeditor_uploader.backends.PillowBackend"
CKEDITOR_THUMBNAIL_SIZE = (300, 300)
CKEDITOR_IMAGE_QUALITY = 40
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}

# CUSTOM_TOOLBAR = [
#     {
#         "name": "document",
#         "items": [
#             "Styles",
#             "Format",
#             "Bold",
#             "Italic",
#             "Underline",
#             "Strike",
#             "-",
#             "TextColor",
#             "BGColor",
#             "-",
#             "JustifyLeft",
#             "JustifyCenter",
#             "JustifyRight",
#             "JustifyBlock",
#         ],
#     },
#     {
#         "name": "widgets",
#         "items": [
#             "Undo",
#             "Redo",
#             "-",
#             "NumberedList",
#             "BulletedList",
#             "-",
#             "Outdent",
#             "Indent",
#             "-",
#             "Link",
#             "Unlink",
#             "-",
#             "Image",
#             "CodeSnippet",
#             "Table",
#             "HorizontalRule",
#             "Smiley",
#             "SpecialChar",
#             "-",
#             "Blockquote",
#             "-",
#             "ShowBlocks",
#             "Maximize",
#         ],
#     },
# ]

# CKEDITOR_CONFIGS = {
#     "default": DEFAULT_CONFIG,
#     "my-custom-toolbar": {
#         "skin": "moono-lisa",
#         "toolbar": CUSTOM_TOOLBAR,
#         "toolbarGroups": None,
#         "extraPlugins": ",".join(["image2", "codesnippet"]),
#         "removePlugins": ",".join(["image"]),
#         "codeSnippet_theme": "xcode",
#     },
# }


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
# AUTH_USER_MODEL = 'auth.User'

# Default redirect URL after login
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
